require('plugs')
require('settings')
require('maps')

require('module.telescope')
require('module.nvim-tree')
require('module.gitsigns')
require('module.toggleterm')
require('module.windline')
require('module.sniprun')
require('module.compe')
require('module.lspconfig')
require('module.lspsaga')
require('module.treesitter')
require('module.lsp-signature')
require('module.tmux_vim_navigator')
